Enable more control over current and non current object transitions and object expirations lifecycle rules
trussworks/terraform-aws-s3-private-bucket pull request #192
Opened 2020-12-02 21:34 UTC by chrisgilmerproj

This change utilizes the `dynamic` blocks in TF13 to allow setting multiple transition blocks on a resource. Here's an example of how this would look:

```hcl
module "s3_bucket" {
  source  = "trussworks/s3-private-bucket/aws"

  bucket = var.bucket_name
  tags   = var.tags

  abort_incomplete_multipart_upload_days = 7

  transitions = [
    {
      days          = 30
      storage_class = "STANDARD_IA"
    },
    {
      days          = 60
      storage_class = "GLACIER"
    },
    {
      days          = 150
      storage_class = "DEEP_ARCHIVE"
    }
  ]

  noncurrent_version_transitions = [
    {
      days          = 30
      storage_class = "STANDARD_IA"
    },
    {
      days          = 60
      storage_class = "GLACIER"
    }
  ]
  noncurrent_version_expiration = 90

  logging_bucket = module.aws_logs.aws_logs_bucket
}
```

The defaults are all set so that this change should be a no-op for folks using the defaults.

2020-12-02 21:58 UTC, eeeady requested changes
This looks like a great change to me. The only thing I'd really appreciate is if you could take your example and put it in the /examples/ directory so it's easy for us to add a terratest and have something for folks to refer to.

Thanks Chris!

2020-12-02 22:09 UTC, chrisgilmerproj commented on examples/transitions/main.tf
> +      storage_class = "DEEP_ARCHIVE"
I should note that moving things to deep archive requires that `days` is 90 days larger than whatever you have for Glacier.

2020-12-02 22:09 UTC, chrisgilmerproj commented
I've added an example. I haven't had to write a test for a module yet so I'm not sure what else you'd like. I could make the transitions all variables so golang could populate them, but that might make things murky. Let me know what I can do!

2020-12-02 22:58 UTC, eeeady approved these changes
LGTM. Thank you for adding an example!

2020-12-02 22:58 UTC, merged

2020-12-02 23:13 UTC, chrisgilmerproj commented
You're welcome! I'll look out for the next version of this. I assume you probably need to write up a golang test (sorry for the extra work!). As usual, thanks for all the help and attention.

2020-12-03 00:00 UTC, eeeady commented
@chrisgilmerproj I needed a break. Here's the release: https://github.com/trussworks/terraform-aws-s3-private-bucket/releases/tag/v3.2.1 I couldn't find a good way to verify the lifecycle rules in like an hour but will follow up later. Didn't want you to wait too long.

2020-12-03 00:14 UTC, chrisgilmerproj commented
I really appreciate it. Thanks!