Update the module based on AWS changes to S3 bucket default settings
trussworks/terraform-aws-s3-private-bucket pull request #401
Opened 2023-05-23 16:43 UTC by jsclarridge

Updates the module to account for changes made by AWS in April 2023 to the default security settings of new S3 buckets.

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

See the proposed changes in the README `Upgrade Paths` section for more details about the module changes.

2023-05-23 17:22 UTC, esacteksab approved these changes

2023-05-24 15:05 UTC, rpdelaney requested changes

2023-05-24 15:26 UTC, rpdelaney commented on variables.tf
> +}
This is potentially helpful if setting a wrong value leads to surprising behavior. If it fails to plan, then we don't need validation.

2023-05-24 18:33 UTC, jsclarridge commented on README.md
> +### Upgrading from 4.x.x to 5.x.x
Can you provide suggested text to add?

2023-05-24 18:39 UTC, rpdelaney commented on README.md
> +
```suggestion
use the new variables will depend on your use case.

Removed variables:
- `sse_algorithm`. If `kms_master_key_id` is not passed, the module will fall back to AES256 for the bucket encryption configuration.

```

2023-05-24 18:39 UTC, rpdelaney commented on README.md
> +### Upgrading from 4.x.x to 5.x.x
I left a suggestion!

2023-05-24 23:13 UTC, jsclarridge commented on README.md
> +### Upgrading from 4.x.x to 5.x.x
Thanks. Added.

2023-05-24 23:13 UTC, jsclarridge commented on variables.tf
> +variable "control_object_ownership" {
Good catch. I updated main.tf to use this variable.

2023-05-24 23:28 UTC, jsclarridge commented on variables.tf
> +}
I like that you're thinking about this, but I don't think the validation is needed. Terraform fails to plan when I use a non-expected ACL, without the additional validation here.

2023-05-24 23:30 UTC, jsclarridge commented on README.md
> +
Added. See note above.

2023-05-25 01:16 UTC, rpdelaney approved these changes

2023-05-25 15:36 UTC, merged